---
- name: Ensure that directory paths exist
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ include_vars_dir_paths }}"
  when: include_vars_dir_paths is defined and include_vars_dir_paths.0 != ""

- name: Get string list of directory paths
  command: "echo '{{ include_vars_dir_paths|join(' ') }}'"
  register: include_vars_string_cmd
  when: include_vars_dir_paths is defined and include_vars_dir_paths.0 != ""

- name: Get list of .yml files
  command: "find {{ include_vars_string_cmd.stdout }} -name '*.yml'"
  register: include_vars_find_cmd
  when: include_vars_string_cmd is defined and include_vars_string_cmd.stdout != ""

- name: Include variables from .yml files found in path
  include_vars: "{{ item }}"
  with_items: "{{ include_vars_find_cmd.stdout_lines | default([]) }}"
  when: include_vars_find_cmd is defined

- name: Print included .yml files
  debug:
    msg: "Attempted to include {{ item }}"
  with_items: "{{ include_vars_find_cmd.stdout_lines | default([]) }}"
  when: include_vars_find_cmd is defined